name: ğŸš€ Deploy a producciÃ³n

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # se ejecuta cuando haces push a la rama main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§° Checkout del repositorio
        uses: actions/checkout@v4

      - name: ğŸ³ Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ—ï¸ Build de la imagen Docker
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mi-app
          TAG=$(date +'%Y%m%d%H%M')  # ejemplo de versiÃ³n por timestamp
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .

      - name: ğŸ“¦ Push de la imagen a Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mi-app
          docker push $IMAGE --all-tags

      # - name: ğŸ” Conectarse al VPS y hacer deploy
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USER }}
      #     key: ${{ secrets.VPS_SSH_KEY }}
      #     script: |
      #       cd /ruta/de/tu/proyecto
      #       docker compose pull
      #       docker compose up -d